### ISSUE TITLE
MisterMenu Web Application: Work Distribution

### ISSUE THREAD

**Issue by jeffrymahbuubi** [mistermenu/mistermenu#1]
#### Figma : 
 - Bang @abdehi  = Menu utama, Rekomendasi
 - Bang @MatchaBear =  Checkout button, Order Cart Page + Confirm Order Button,  Order Summary.

#### Kontenbase : 
 - Bang @jeffrymahbuubi = Foto, Nama, Harga, Kategori

**Comment by mistermenu4** [comment]
DONE
